### PR TITLE
Update app.yaml

### PR DESCRIPTION
**Pull request by jayunit100**
update release to latest LTR release that is downloaded from the website

### CODE REVIEW

**Comment by knisbet** [comment]
Thanks for your contribution.

I think tele will now use it's own version as the runtimeVersion if it's not specified. I don't remember what version that came into effect off hand, but I think it should be 5.5.0 and later. Probably a better approach so we don't have to PR it every couple of months.

**Comment by jayunit100** [comment]
ok, but can we merge this as a fix to the current repository ? otherwise i think this things wont work out of the box - then once tele is smart enough we dont have to maintain it anymore.

I needed to do this to get this to work.  Was i doing something wrong?

**Comment by knisbet** [comment]
No, you're not doing anything wrong. It's just I'm recommending a slightly different fix. 

As of version 5.5.0-beta.1 (commit: https://github.com/gravitational/gravity/commit/1f5197d063c3171e125012add14a1386d2669531)  tele supports an application manifest with the runtime version unset. When building an app with the version unset, it will use the version of tele to find the matching runtime.

So basically, instead of bumping the version to 5.5.8, I would comment out the field, and then we don't encounter the same sort of issue with a later release.

**Comment by benarent** [comment]
@knisbet I've a PR based on your feedback.

**Pull request closed without merging**
